name: supabase_auth_ui
description: A Flutter project with Supabase authentication and beautiful UI.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.3
  cupertino_icons: ^1.0.2
  go_router: ^14.6.3
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
